// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "536d8d8d-d66a-47e8-ba45-06eaa32e9d94");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575453343);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575453463);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575452863);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575453103);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575452983);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575453223);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575453703);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575453583);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575452833);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a6497181-eda9-440f-8565-609cb6095689}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575446400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575452864001");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575454688001");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575452843337");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575456443337");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575452837");
user_pref("browser.slowStartup.averageTime", 7392);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575452840048");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "3078663aaaa44a1381605d6fb198fa52");
user_pref("extensions.blocklist.lastModified", "Tue, 03 Dec 2019 12:43:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575453347);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ac30eb03-1f16-4d34-8da4-4e723d5bc52b\",\"screenshots@mozilla.org\":\"15ee729b-4ccd-46e5-a190-89d9292c1566\",\"webcompat-reporter@mozilla.org\":\"fee50250-dc90-4b30-bd51-4db700e33914\",\"webcompat@mozilla.org\":\"13f9a987-86ef-4fe8-ae2d-0dc7159bb278\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575452989);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575452988);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4ee16f78-9869-41a5-b0ea-2a554a7bb33b");
user_pref("security.sandbox.plugin.tempDirSuffix", "5a02c95c-c56a-4e57-83e1-5637528905a1");
user_pref("services.blocklist.addons.checked", 1575453012);
user_pref("services.blocklist.gfx.checked", 1575453012);
user_pref("services.blocklist.onecrl.checked", 1575453012);
user_pref("services.blocklist.pinning.checked", 1575453012);
user_pref("services.blocklist.plugins.checked", 1575453012);
user_pref("services.settings.clock_skew_seconds", -89);
user_pref("services.settings.last_etag", "\"1575448918517\"");
user_pref("services.settings.last_update_seconds", 1575453311);
user_pref("services.settings.main.language-dictionaries.last_check", 1575453012);
user_pref("services.settings.main.sites-classification.last_check", 1575453012);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575452829);
user_pref("toolkit.telemetry.cachedClientID", "e3e43487-81e3-463d-a6ea-4812a779bfb9");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
